{
    "phase": 1,
    "question": "What position does the player who played for butler cc (ks) play?",
    "table": {
        "header": [
            "Player",
            "No.",
            "Nationality",
            "Position",
            "Years in Toronto",
            "School/Club Team",
        ],
        "page_title": "Toronto Raptors all-time roster",
        "page_id": "",
        "types": ["text", "text", "text", "text", "text", "text"],
        "id": "1-10015132-11",
        "section_title": "L",
        "caption": "L",
        "rows": [
            [
                "Antonio Lang",
                "21",
                "United States",
                "Guard-Forward",
                "1999-2000",
                "Duke",
            ],
            ["Voshon Lenard", "2", "United States", "Guard", "2002-03", "Minnesota"],
            [
                "Martin Lewis",
                "32, 44",
                "United States",
                "Guard-Forward",
                "1996-97",
                "Butler CC (KS)",
            ],
            ["Brad Lohaus", "33", "United States", "Forward-Center", "1996", "Iowa"],
            [
                "Art Long",
                "42",
                "United States",
                "Forward-Center",
                "2002-03",
                "Cincinnati",
            ],
            ["John Long", "25", "United States", "Guard", "1996-97", "Detroit"],
            ["Kyle Lowry", "3", "United States", "Guard", "2012-Present", "Villanova"],
        ],
        "name": "table_10015132_11",
    },
    "sql": {
        "human_readable": "SELECT Position FROM table WHERE School/Club Team = Butler CC (KS)",
        "sel": 3,
        "agg": 0,
        "conds": {
            "column_index": [5],
            "operator_index": [0],
            "condition": ["Butler CC (KS)"],
        },
    },
}

{
    "phase": 1,
    "question": "The common of Chieri has what population density?",
    "table": {
        "header": [
            "Rank",
            "Common of",
            "Population",
            "Area (km 2 )",
            "Density (inhabitants/km 2 )",
            "Altitude (mslm)",
        ],
        "page_title": "Province of Turin",
        "page_id": "",
        "types": ["text", "text", "real", "text", "text", "real"],
        "id": "1-1449176-1",
        "section_title": "",
        "caption": "See also",
        "rows": [
            ["1st", "Torino", "907563", "130.7", "6943.9", "239"],
            ["2nd", "Moncalieri", "58320", "47.3", "1233", "260"],
            ["3rd", "Collegno", "50137", "18.0", "2785.4", "302"],
            ["4th", "Rivoli", "49591", "29.2", "1698.3", "352"],
            ["5th", "Nichelino", "48946", "20.4", "2399.3", "229"],
            ["6th", "Settimo Torinese", "47988", "32.7", "1467.5", "207"],
            ["7th", "Grugliasco", "37870", "13", "2913.1", "293"],
            ["8th", "Chieri", "36168", "50", "723.4", "376"],
            ["9th", "Pinerolo", "36158", "54", "667", "305"],
        ],
        "name": "table_1449176_1",
    },
    "sql": {
        "human_readable": "SELECT Density (inhabitants/km 2 ) FROM table WHERE Common of = Chieri",
        "sel": 4,
        "agg": 0,
        "conds": {"column_index": [1], "operator_index": [0], "condition": ["Chieri"]},
    },
}
